# Paths in this file can either be absolute or relative to this repositories location on your machine

# The root of your gclient configured directory, this is the directory containing the "src" folder
electronRoot: /Users/me/projects/electron-gn

# The path to a directory to use as your chromium git cache, this directory must exist
gitCachePath: .git-cache

# (Optional): The name of the "out/X" directory to use, default is "Debug"
# electronOutDir: Debug

# (Optional): The name of the build config to use, default is "debug".  Possible values are debug, testing and release
# buildType: debug

# (Optional): Whether or not git should use HTTPS or SSH; uses SSH by default
# gitUseHttps: true

# (Optional): Any extra arguments to pass to GN, useful for setting up a MAS build
# extraGnArgs:
